[project]
name = "openai-kokoro-tts"
version = "0.1.0"
description = "Present Kokoro TTS as an OpenAI API compatible endpoint"
readme = "README.md"
requires-python = ">=3.11,<3.12"
authors = [
  { name = "Matthew Hand", email = "matthewhandau@gmail.com" }
]
dependencies = [
    "flask>=3.1.0",
    "munch>=4.0.0",
    "onnxruntime>=1.20.1",
    "phonemizer>=3.3.0",
    "pydub>=0.25.1",
    "python-dotenv>=1.0.1",
    "scipy>=1.15.0",
    "soundfile>=0.13.0",
    "torch>=1.0.0",
    "torchvision>=0.20.1",
    "transformers>=4.48.0",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]

[tool.pytest.ini_options]
pythonpath = [
    ".",          # Add project root
    "models/kokoro"  # Add the path to the Kokoro module
]
